[build]
  command = "npm install"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 3001
  publish = "public"
  functions = "functions" 